Delete SmokeTest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -116,43 +116,43 @@ jobs :
           docker build -t tomatano/devops_tpfilrouge:latest .
           docker push tomatano/devops_tpfilrouge:latest
 
-  smoke_test:
-    runs-on: ubuntu-latest
-    needs: build_and_push_docker_image
-    steps:
-      - name: Pull Docker image
-        run: docker pull tomatano/devops_tpfilrouge:latest
+  # smoke_test:
+  #   runs-on: ubuntu-latest
+  #   needs: build_and_push_docker_image
+  #   steps:
+  #     - name: Pull Docker image
+  #       run: docker pull tomatano/devops_tpfilrouge:latest
 
-      - name: Run container
-        run: |
-          docker run -d --name smoke-test -p 3000:3000 tomatano/devops_tpfilrouge:latest
+  #     - name: Run container
+  #       run: |
+  #         docker run -d --name smoke-test -p 3000:3000 tomatano/devops_tpfilrouge:latest
 
-      - name: Wait for service to be ready
-        run: |
-          for i in {1..30}; do
-            if curl -sf http://localhost:3000/api/docs > /dev/null; then
-              echo "Service prêt !"
-              exit 0
-            fi
-            echo "Attente du service... ($i/30)"
-            sleep 2
-          done
-          echo "Le service n'a jamais répondu"
-          docker logs smoke-test
-          exit 1
+  #     - name: Wait for service to be ready
+  #       run: |
+  #         for i in {1..30}; do
+  #           if curl -sf http://localhost:3000/api/docs > /dev/null; then
+  #             echo "Service prêt !"
+  #             exit 0
+  #           fi
+  #           echo "Attente du service... ($i/30)"
+  #           sleep 2
+  #         done
+  #         echo "Le service n'a jamais répondu"
+  #         docker logs smoke-test
+  #         exit 1
 
-      - name: Smoke test HTTP request
-        run: |
-          status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/api/docs)
-          echo "Code HTTP reçu : $status"
-          if [ "$status" -ne 200 ]; then
-            echo "Smoke test KO"
-            docker logs smoke-test
-            exit 1
-          fi
-          echo "Smoke test OK"
+  #     - name: Smoke test HTTP request
+  #       run: |
+  #         status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:3000/api/docs)
+  #         echo "Code HTTP reçu : $status"
+  #         if [ "$status" -ne 200 ]; then
+  #           echo "Smoke test KO"
+  #           docker logs smoke-test
+  #           exit 1
+  #         fi
+  #         echo "Smoke test OK"
 
-      - name: Cleanup
-        if: always()
-        run: docker rm -f smoke-test || true
+  #     - name: Cleanup
+  #       if: always()
+  #       run: docker rm -f smoke-test || true
     
